import os
import tempfile
import unittest

import openpyxl
from openpyxl.styles import Font

import paper_serializers
from app_helpers import detect_tables_in_sheet
from Spreadsheet_LLM_Encoder import spreadsheet_llm_encode


BOLD = Font(bold=True)


def _bold_row(ws, row, start_col, values):
    for offset, value in enumerate(values):
        cell = ws.cell(row=row, column=start_col + offset, value=value)
        cell.font = BOLD


def _write_rows(ws, start_row, start_col, rows):
    for r_offset, row in enumerate(rows):
        for c_offset, value in enumerate(row):
            ws.cell(row=start_row + r_offset, column=start_col + c_offset, value=value)


def _simple_table():
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Sheet1"
    _bold_row(ws, 1, 1, ["Region", "Revenue", "Cost"])
    _write_rows(ws, 2, 1, [["West", 100, 40], ["East", 120, 55]])
    return wb, {
        "detected_ranges": ["A1:C3"],
        "prompt_contains": ["(Region|", "(Revenue|", "(Cost|"],
        "remap_ranges": ["A1:C3"],
        "anchor_rows_any": [1, 3],
        "anchor_cols_any": ["A", "C"],
    }


def _merged_header():
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Sheet1"
    ws.merge_cells("A1:C1")
    ws["A1"] = "Quarterly Revenue"
    ws["A1"].font = BOLD
    _bold_row(ws, 2, 1, ["Region", "Q1", "Q2"])
    _write_rows(ws, 3, 1, [["West", 10, 20], ["East", 30, 40]])
    return wb, {
        "detected_ranges": ["A1:C4"],
        "prompt_contains": ["(Quarterly Revenue|", "(Region|", "(Q1|"],
        "remap_ranges": ["A1:C4"],
        "anchor_rows_any": [1, 4],
        "anchor_cols_any": ["A", "C"],
    }


def _side_by_side_tables():
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Sheet1"
    _bold_row(ws, 1, 1, ["Product", "Sales"])
    _bold_row(ws, 1, 4, ["Region", "Cost"])
    _write_rows(ws, 2, 1, [["A", 10], ["B", 20]])
    _write_rows(ws, 2, 4, [["West", 4], ["East", 8]])
    return wb, {
        "detected_ranges": ["A1:B3", "D1:E3"],
        "prompt_contains": ["(Product|", "(Sales|", "(Region|", "(Cost|"],
        "remap_ranges": ["A1:B3", "D1:E3"],
        "anchor_rows_any": [1, 3],
        "anchor_cols_any": ["A", "B", "D", "E"],
    }


def _notes_above_table():
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Sheet1"
    ws["A1"] = "Draft export generated by finance"
    _bold_row(ws, 3, 1, ["Account", "Amount", "Owner"])
    _write_rows(ws, 4, 1, [["Cash", 1000, "Mia"], ["AR", 500, "Leo"]])
    return wb, {
        "detected_ranges": ["A3:C5"],
        "prompt_contains": ["(Draft export generated by finance|", "(Account|"],
        "remap_ranges": ["A3:C5"],
        "anchor_rows_any": [3, 5],
        "anchor_cols_any": ["A", "C"],
    }


def _sparse_sheet_table():
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Sheet1"
    _bold_row(ws, 5, 1, ["ID", "Score", "Status"])
    _write_rows(ws, 6, 1, [[1, 0.91, "ok"], [2, 0.82, "hold"]])
    return wb, {
        "detected_ranges": ["A5:C7"],
        "prompt_contains": ["(ID|", "(Score|", "(Status|"],
        "remap_ranges": ["A5:C7"],
        "anchor_rows_any": [5, 7],
        "anchor_cols_any": ["A", "C"],
    }


def _date_year_headers():
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Sheet1"
    _bold_row(ws, 1, 1, ["Metric", 2022, 2023, 2024])
    for cell in ("B1", "C1", "D1"):
        ws[cell].number_format = "yyyy"
    _write_rows(ws, 2, 1, [["Revenue", 10, 20, 30], ["Cost", 4, 8, 12]])
    return wb, {
        "detected_ranges": ["A1:D3"],
        "prompt_contains": ["(Metric|", "(yyyy|", "(IntNum|"],
        "remap_ranges": ["A1:C3"],
        "anchor_rows_any": [1, 3],
        "anchor_cols_any": ["A", "C"],
    }


def _totals_with_formula():
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Sheet1"
    _bold_row(ws, 1, 1, ["Item", "Units", "Price", "Total"])
    _write_rows(ws, 2, 1, [["A", 2, 5, "=B2*C2"], ["B", 3, 7, "=B3*C3"]])
    ws["A4"] = "Grand Total"
    ws["D4"] = "=SUM(D2:D3)"
    ws["A4"].font = BOLD
    return wb, {
        "detected_ranges": ["A1:D4"],
        "prompt_contains": ["(Item|", "(Units|", "(Price|", "(Total|"],
        "remap_ranges": ["A1:D4"],
        "anchor_rows_any": [1, 4],
        "anchor_cols_any": ["A", "D"],
    }


def _vertical_multi_table():
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Sheet1"
    _bold_row(ws, 1, 1, ["Product", "Sales"])
    _write_rows(ws, 2, 1, [["A", 10], ["B", 20]])
    _bold_row(ws, 5, 1, ["Region", "Cost", "Margin"])
    _write_rows(ws, 6, 1, [["West", 4, 0.6], ["East", 8, 0.5]])
    return wb, {
        "detected_ranges": ["A1:B3", "A5:C7"],
        "prompt_contains": ["(Product|", "(Region|", "(Margin|"],
        "remap_ranges": ["A1:B3", "A5:C7"],
        "anchor_rows_any": [1, 7],
        "anchor_cols_any": ["A", "C"],
    }


def _formatted_numbers():
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Sheet1"
    _bold_row(ws, 1, 1, ["Month", "Revenue", "Rate"])
    _write_rows(ws, 2, 1, [["Jan", 1200.25, 0.15], ["Feb", 900.50, 0.20]])
    for cell in ("B2", "B3"):
        ws[cell].number_format = "$#,##0.00"
    for cell in ("C2", "C3"):
        ws[cell].number_format = "0.00%"
    return wb, {
        "detected_ranges": ["A1:C3"],
        "prompt_contains": ["(Month|", "($#,##0.00|", "(PercentageNum|"],
        "remap_ranges": ["A1:C3"],
        "anchor_rows_any": [1, 3],
        "anchor_cols_any": ["A", "C"],
    }


def _hidden_row_table():
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Sheet1"
    _bold_row(ws, 1, 1, ["Name", "Value"])
    _write_rows(ws, 2, 1, [["Internal", 1], ["External", 2]])
    ws.row_dimensions[2].hidden = True
    return wb, {
        "detected_ranges": ["A1:B3"],
        "prompt_contains": ["(Name|", "(Value|", "(Internal|", "(External|"],
        "remap_ranges": ["A1:B3"],
        "anchor_rows_any": [1, 3],
        "anchor_cols_any": ["A", "B"],
    }


FIXTURES = [
    ("simple_table", _simple_table),
    ("merged_header", _merged_header),
    ("side_by_side_tables", _side_by_side_tables),
    ("notes_above_table", _notes_above_table),
    ("sparse_sheet_table", _sparse_sheet_table),
    ("date_year_headers", _date_year_headers),
    ("totals_with_formula", _totals_with_formula),
    ("vertical_multi_table", _vertical_multi_table),
    ("formatted_numbers", _formatted_numbers),
    ("hidden_row_table", _hidden_row_table),
]


class TestPaperParityFixtures(unittest.TestCase):
    def test_fixture_suite_has_paper_parity_expectations(self):
        self.assertEqual(10, len(FIXTURES))
        with tempfile.TemporaryDirectory() as tmpdir:
            for name, builder in FIXTURES:
                with self.subTest(name=name):
                    wb, expected = builder()
                    path = os.path.join(tmpdir, f"{name}.xlsx")
                    wb.save(path)

                    loaded = openpyxl.load_workbook(path, data_only=False)
                    detected = [
                        table["full_range"]
                        for table in detect_tables_in_sheet(loaded["Sheet1"])
                    ]
                    for rng in expected["detected_ranges"]:
                        self.assertIn(rng, detected)

                    encoding = spreadsheet_llm_encode(path, k=1, paper_strict=True)
                    sheet = encoding["sheets"]["Sheet1"]
                    rows = set(sheet["structural_anchors"]["rows"])
                    cols = set(sheet["structural_anchors"]["columns"])
                    self.assertTrue(rows.intersection(expected["anchor_rows_any"]))
                    self.assertTrue(cols.intersection(expected["anchor_cols_any"]))

                    prompt = paper_serializers.to_paper_compressed_prompt(
                        sheet, coord_map=sheet["coord_map"]
                    )
                    for token in expected["prompt_contains"]:
                        self.assertIn(token, prompt)

                    for rng in expected["remap_ranges"]:
                        compact = paper_serializers.remap_range(rng, sheet["coord_map"])
                        self.assertIsNotNone(compact, rng)
                        self.assertEqual(
                            rng,
                            paper_serializers.unremap_range(compact, sheet["coord_map"]),
                        )


if __name__ == "__main__":
    unittest.main()
